// Export all types from a single entry point
export * from './common';
export * from './api';
export * from './components';

// Re-export commonly used types for convenience
export type {
  // Common types
  Optional,
  Required,
  DeepPartial,
  ApiResponse,
  PaginatedResponse,
  ApiError,
  ValidationError,
  LoadingState,
  CacheItem,
  CacheOptions,
  FormField,
  FormState,
  BaseComponentProps,
  ButtonProps,
  InputProps,
  A11yProps,
  Theme,
  RouteConfig,
  StoreState,
  StoreAction,
  UseAsyncOptions,
  UseAsyncResult,
  DebounceFunction,
  ThrottleFunction,
  EventHandler,
  AsyncEventHandler,
  Id,
  Timestamp,
  Status,
  Size,
  Variant,
  Position,
  Alignment,
} from './common';

export type {
  // API types
  User,
  UserRole,
  UserProfile,
  UserPreferences,
  UserStatistics,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  Student,
  StudentProgress,
  StudentDashboard,
  Teacher,
  TeacherStatistics,
  TeacherDashboard,
  Admin,
  AdminPermission,
  AdminStatistics,
  SystemHealth,
  Batch,
  CreateBatchRequest,
  UpdateBatchRequest,
  Quiz,
  QuizType,
  Question,
  QuestionType,
  Difficulty,
  QuizAttempt,
  QuizAnswer,
  PracticeSession,
  PracticeType,
  Operation,
  LeaderboardEntry,
  LeaderboardResponse,
  Activity,
  ActivityType,
  Achievement,
  AchievementCategory,
  AchievementCriteria,
  Event,
  EventType,
  Report,
  ReportType,
  ReportData,
  ChartData,
  TableData,
  ReportFilters,
  ApiEndpoints,
} from './api';

export type {
  // Component types
  LayoutProps,
  HeaderProps,
  BreadcrumbItem,
  SidebarProps,
  SidebarItem,
  NavBarProps,
  NavItem,
  UserMenuProps,
  UserMenuItem,
  ModalProps,
  ConfirmModalProps,
  FormProps,
  FieldProps,
  SelectOption,
  FieldValidation,
  TableProps,
  Column,
  PaginationProps,
  SortingProps,
  SelectionProps,
  TableAction,
  CardProps,
  StatCardProps,
  ChartProps,
  LoadingProps,
  SkeletonProps,
  AlertProps,
  BadgeProps,
  TooltipProps,
  DropdownProps,
  DropdownItem,
  TabsProps,
  TabItem,
  AccordionProps,
  AccordionItem,
  StepperProps,
  StepItem,
  ProgressProps,
  AvatarProps,
  TagProps,
  DividerProps,
  SpaceProps,
  GridProps,
  GridItemProps,
  PortalProps,
  TransitionProps,
  HOCProps,
  HOC,
} from './components';
