# Generated by Django 4.2.5 on 2025-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
