# Generated by Django 4.2.5 on 2025-08-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_organizationtag_expirationdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
            options={
                'db_table': 'Authentication_userstreak',
                'unique_together': {('user',)},
            },
        ),
        migrations.RemoveField(
            model_name='pvpgamesession',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='pvpgamesession',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='pvpplayeranswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pvpplayeranswer',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='pvpplayeranswer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='pvpplayeranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pvproom',
            name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='pvproomplayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pvproomplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='pvproomplayer',
            name='room',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='user',
        ),
        migrations.DeleteModel(
            name='PVPGameResult',
        ),
        migrations.DeleteModel(
            name='PVPGameSession',
        ),
        migrations.DeleteModel(
            name='PVPPlayerAnswer',
        ),
        migrations.DeleteModel(
            name='PVPRoom',
        ),
        migrations.DeleteModel(
            name='PVPRoomPlayer',
        ),
        migrations.DeleteModel(
            name='UserExperience',
        ),
    ]
